// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: UI

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_hienthi
void ui_hienthi_screen_init(void);
void ui_event_hienthi(lv_event_t * e);
lv_obj_t * ui_hienthi;
lv_obj_t * ui_doAmHT;
lv_obj_t * ui_anhSangHT;
lv_obj_t * ui_nhietDoHT;
lv_obj_t * ui_nhietDo_txt;
lv_obj_t * ui_doAm_txt;
lv_obj_t * ui_anhSang_txt;
lv_obj_t * ui_time;
// CUSTOM VARIABLES
lv_obj_t * uic_hienthi;
lv_obj_t * uic_doAmHT;
lv_obj_t * uic_anhSangHT;
lv_obj_t * uic_nhietDoHT;
lv_obj_t * uic_nhietDo_txt;
lv_obj_t * uic_doAm_txt;
lv_obj_t * uic_anhSang_txt;
lv_obj_t * uic_time1;

// SCREEN: ui_dieuKhien
void ui_dieuKhien_screen_init(void);
void ui_event_dieuKhien(lv_event_t * e);
lv_obj_t * ui_dieuKhien;
lv_obj_t * ui_bom;
lv_obj_t * ui_den;
lv_obj_t * ui_batbom;
lv_obj_t * ui_baden;
// CUSTOM VARIABLES
lv_obj_t * uic_dieuKhien;
lv_obj_t * uic_bom;
lv_obj_t * uic_den;
lv_obj_t * uic_batbom;
lv_obj_t * uic_baden;

// SCREEN: ui_setUp
void ui_setUp_screen_init(void);
void ui_event_setUp(lv_event_t * e);
lv_obj_t * ui_setUp;
lv_obj_t * ui_doAmSetUp;
lv_obj_t * ui_anhSangSetup;
lv_obj_t * ui_SetupAm;
lv_obj_t * ui_Setupsang;
// CUSTOM VARIABLES
lv_obj_t * uic_setUp;
lv_obj_t * uic_doAmSetUp;
lv_obj_t * uic_anhSangSetup;
lv_obj_t * uic_Sli_Am;
lv_obj_t * uic_Sli_sang;

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_hienthi(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_dieuKhien, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_dieuKhien_screen_init);
    }
}

void ui_event_dieuKhien(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_setUp, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_setUp_screen_init);
    }
}

void ui_event_setUp(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_hienthi, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_hienthi_screen_init);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_hienthi_screen_init();
    ui_dieuKhien_screen_init();
    ui_setUp_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_hienthi);
}
