// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: UI

#ifndef _UI_UI_H
#define _UI_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"
#include "ui_theme_manager.h"
#include "ui_themes.h"

// SCREEN: ui_hienthi
void ui_hienthi_screen_init(void);
void ui_event_hienthi(lv_event_t * e);
extern lv_obj_t * ui_hienthi;
extern lv_obj_t * ui_doAmHT;
extern lv_obj_t * ui_anhSangHT;
extern lv_obj_t * ui_nhietDoHT;
extern lv_obj_t * ui_nhietDo_txt;
extern lv_obj_t * ui_doAm_txt;
extern lv_obj_t * ui_anhSang_txt;
extern lv_obj_t * ui_time;
// CUSTOM VARIABLES
extern lv_obj_t * uic_hienthi;
extern lv_obj_t * uic_doAmHT;
extern lv_obj_t * uic_anhSangHT;
extern lv_obj_t * uic_nhietDoHT;
extern lv_obj_t * uic_nhietDo_txt;
extern lv_obj_t * uic_doAm_txt;
extern lv_obj_t * uic_anhSang_txt;
extern lv_obj_t * uic_time1;

// SCREEN: ui_dieuKhien
void ui_dieuKhien_screen_init(void);
void ui_event_dieuKhien(lv_event_t * e);
extern lv_obj_t * ui_dieuKhien;
extern lv_obj_t * ui_bom;
extern lv_obj_t * ui_den;
extern lv_obj_t * ui_batbom;
extern lv_obj_t * ui_baden;
// CUSTOM VARIABLES
extern lv_obj_t * uic_dieuKhien;
extern lv_obj_t * uic_bom;
extern lv_obj_t * uic_den;
extern lv_obj_t * uic_batbom;
extern lv_obj_t * uic_baden;

// SCREEN: ui_setUp
void ui_setUp_screen_init(void);
void ui_event_setUp(lv_event_t * e);
extern lv_obj_t * ui_setUp;
extern lv_obj_t * ui_doAmSetUp;
extern lv_obj_t * ui_anhSangSetup;
extern lv_obj_t * ui_SetupAm;
extern lv_obj_t * ui_Setupsang;
// CUSTOM VARIABLES
extern lv_obj_t * uic_setUp;
extern lv_obj_t * uic_doAmSetUp;
extern lv_obj_t * uic_anhSangSetup;
extern lv_obj_t * uic_Sli_Am;
extern lv_obj_t * uic_Sli_sang;

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
