// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: UI

#include "ui.h"

void ui_dieuKhien_screen_init(void)
{
    ui_dieuKhien = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_dieuKhien, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_bom = lv_switch_create(ui_dieuKhien);
    lv_obj_set_width(ui_bom, 50);
    lv_obj_set_height(ui_bom, 25);
    lv_obj_set_x(ui_bom, -33);
    lv_obj_set_y(ui_bom, -12);
    lv_obj_set_align(ui_bom, LV_ALIGN_CENTER);

    ui_den = lv_switch_create(ui_dieuKhien);
    lv_obj_set_width(ui_den, 50);
    lv_obj_set_height(ui_den, 25);
    lv_obj_set_x(ui_den, -32);
    lv_obj_set_y(ui_den, 28);
    lv_obj_set_align(ui_den, LV_ALIGN_CENTER);

    ui_batbom = lv_label_create(ui_dieuKhien);
    lv_obj_set_width(ui_batbom, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_batbom, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_batbom, 43);
    lv_obj_set_y(ui_batbom, -14);
    lv_obj_set_align(ui_batbom, LV_ALIGN_CENTER);
    lv_label_set_text(ui_batbom, "bat bom");

    ui_baden = lv_label_create(ui_dieuKhien);
    lv_obj_set_width(ui_baden, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_baden, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_baden, 40);
    lv_obj_set_y(ui_baden, 27);
    lv_obj_set_align(ui_baden, LV_ALIGN_CENTER);
    lv_label_set_text(ui_baden, "bat den");

    lv_obj_add_event_cb(ui_dieuKhien, ui_event_dieuKhien, LV_EVENT_ALL, NULL);
    uic_dieuKhien = ui_dieuKhien;
    uic_bom = ui_bom;
    uic_den = ui_den;
    uic_batbom = ui_batbom;
    uic_baden = ui_baden;

}
