// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: UI

#include "ui.h"

void ui_setUp_screen_init(void)
{
    ui_setUp = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_setUp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_doAmSetUp = lv_label_create(ui_setUp);
    lv_obj_set_width(ui_doAmSetUp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_doAmSetUp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_doAmSetUp, -36);
    lv_obj_set_y(ui_doAmSetUp, -27);
    lv_obj_set_align(ui_doAmSetUp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_doAmSetUp, "do am dat : --%");
    lv_obj_set_style_text_font(ui_doAmSetUp, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_anhSangSetup = lv_label_create(ui_setUp);
    lv_obj_set_width(ui_anhSangSetup, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_anhSangSetup, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_anhSangSetup, -39);
    lv_obj_set_y(ui_anhSangSetup, 22);
    lv_obj_set_align(ui_anhSangSetup, LV_ALIGN_CENTER);
    lv_label_set_text(ui_anhSangSetup, "anh sang : --%");
    lv_label_set_recolor(ui_anhSangSetup, "true");
    lv_obj_set_style_text_font(ui_anhSangSetup, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SetupAm = lv_slider_create(ui_setUp);
    lv_slider_set_value(ui_SetupAm, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_SetupAm) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_SetupAm, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_SetupAm, 140);
    lv_obj_set_height(ui_SetupAm, 10);
    lv_obj_set_x(ui_SetupAm, 2);
    lv_obj_set_y(ui_SetupAm, -5);
    lv_obj_set_align(ui_SetupAm, LV_ALIGN_CENTER);

    ui_Setupsang = lv_slider_create(ui_setUp);
    lv_slider_set_value(ui_Setupsang, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Setupsang) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Setupsang, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Setupsang, 140);
    lv_obj_set_height(ui_Setupsang, 10);
    lv_obj_set_x(ui_Setupsang, 2);
    lv_obj_set_y(ui_Setupsang, 45);
    lv_obj_set_align(ui_Setupsang, LV_ALIGN_CENTER);

    lv_obj_add_event_cb(ui_setUp, ui_event_setUp, LV_EVENT_ALL, NULL);
    uic_setUp = ui_setUp;
    uic_doAmSetUp = ui_doAmSetUp;
    uic_anhSangSetup = ui_anhSangSetup;
    uic_Sli_Am = ui_SetupAm;
    uic_Sli_sang = ui_Setupsang;

}
